{
  "changes": [
    "Added explicit numeric range validation for key categories in setConfigKey: percentage (ends in '_pct'), position count, cooldown minutes, inventory scan interval, and option delta ranges."
  ],
  "updatedCode": "const NUMERIC_KEYS = new Set([\n  'max_positions', 'max_notional_per_trade', 'max_daily_loss_pct',\n  'stop_loss_pct', 'take_profit_pct', 'cooldown_minutes',\n  'min_sentiment_score', 'min_analyst_confidence', 'scan_interval_minutes',\n  'position_size_pct',\n  // Options-specific\n  'options_max_premium_per_trade', 'options_max_daily_loss', 'options_max_positions',\n  'options_scalp_take_profit_pct', 'options_scalp_stop_loss_pct',\n  'options_swing_take_profit_pct', 'options_swing_stop_loss_pct',\n  'options_min_conviction', 'options_close_before_minutes',\n  'options_min_delta', 'options_max_delta', 'options_max_spread_pct',\n  'options_cooldown_minutes',\n]);",
  "updatedCode": "if (key.includes('pct') && (value < 0 || value > 1)) {\n    return { success: false, error: `\`${key}\` must be between 0 and 1 (e.g. 0.05 for 5%). Got: \`${value}\`` };\n  }\n  if (key === 'max_positions' && (value < 1 || value > 50)) {\n    return { success: false, error: `\`max_positions\` must be between 1 and 50. Got: \`${value}\`` };\n  }\n  if (key === 'max_notional_per_trade' && value < 10) {\n    return { success: false, error: `\`max_notional_per_trade\` must be at least $10. Got: \`${value}\`` };\n  }\n  if (key === 'cooldown_minutes' && (value < 0 || value > 1440)) {\n    return { success: false, error: `\`cooldown_minutes\` must be 0–1440. Got: \`${value}\`` };\n  }\n  if (key === 'scan_interval_minutes' && (value < 1 || value > 60)) {\n    return { success: false, error: `\`scan_interval_minutes\` must be 1–60. Got: \`${value}\`` };\n  }\n  if (key.includes('delta') && (value < 0 || value > 1)) {\n    return { success: false, error: `\`${key}\` must be between 0 and 1. Got: \`${value}\`` };\n  }\n  if (key.endsWith('_minutes') && value < 1) {\n    return { success: false, error: `\`${key}\` must be at least 1. Got: \`${value}\`` };\n  }",
  "addedCode": "console.log(`[Policy] Config set: ${key} = ${JSON.stringify(value)}`);",
  "addedCode": "// Keys that accept percentage values (0‑1 range) – enhance validation clarity\nconst PCT_KEYS = new Set([\n  'max_daily_loss_pct',\n  'stop_loss_pct',\n  'take_profit_pct',\n  'min_sentiment_score',\n  'min_analyst_confidence',\n  'options_scalp_take_profit_pct',\n  'options_scalp_stop_loss_pct',\n  'options_swing_take_profit_pct',\n  'options_swing_stop_loss_pct',\n]);",
  "addedCode": "if (PCT_KEYS.has(key) && (value < 0 || value > 1)) {\n    return { success: false, error: `\`${key}\` must be a decimal between 0 and 1 (e.g., 0.05 = 5%). Got: \`${value}\`` };\n  }",
  "addedCode": "// Cooldown in minutes – ensure minimum 1 minute\nif (key === 'cooldown_minutes' && (value < 0 || value > 1440)) {\n  return { success: false, error: `\`cooldown_minutes\` must be between 0 and 1440. Got: \`${value}\`` };\n}",
  "addedCode": "// Scan interval – ensure reasonable frequency\nif (key === 'scan_interval_minutes' && (value < 1 || value > 60)) {\n  return { success: false, error: `\`scan_interval_minutes\` must be between 1 and 60. Got: \`${value}\`` };\n}",
  "addedCode": "// Delta range – keep within 0‑1\nif (key === 'options_min_delta' && (value <= 0 || value > 1)) {\n  return { success: false, error: `\`options_min_delta\` must be positive and <= 1. Got: \`${value}\`` };\n}\nif (key === 'options_max_delta' && (value <= 0 || value > 1)) {\n  return { success: false, error: `\`options_max_delta\` must be positive and <= 1. Got: \`${value}\`` };\n}",
  "addedCode": "// Lot size – enforce minimum\nif (key === 'max_positions' && value < 1) {\n  return { success: false, error: `\`max_positions\` must be at least 1. Got: \`${value}\`` };\n}\nif (key === 'max_positions' && value > 50) {\n  return { success: false, error: `\`max_positions\` cannot exceed 50. Got: \`${value}\`` };\n}",
  "addedCode": "// Notional threshold – enforce sensible floor\nif (key === 'max_notional_per_trade' && value < 10) {\n  return { success: false, error: `\`max_notional_per_trade\` must be at least $10. Got: \`${value}\`` };\n}",
  "updatedCode": "const LIST_KEYS = new Set([\n  'symbol_allowlist', 'symbol_denylist', 'options_underlyings',\n]);",
  "updatedCode": "console.log('[Policy] Config updated:', JSON.stringify(updates));",
  "addedCode": "// Reduce config size on disk — save only essential fields\nthis._storage.set('config', { ...this.config });",
  "addedCode": "console.log(`[Policy] Adjusting config for ${key} = ${value}`);",
  "updatedCode": "if (key === 'min_sentiment_score' && value > 1) { \n    return { success: false, error: \`\\`min_sentiment_score\` must be between -1 and 1. Got: ${value}\\`; }\n  }",
  "updatedCode": "if (key === 'min_analyst_confidence' && value > 1) { \n    return { success: false, error: \`\\`min_analyst_confidence\` must be between 0 and 1. Got: ${value}\\`; }\n  }",
  "updatedCode": "if (key === 'options_max_daily_loss' && value < 0) { \n    return { success: false, error: \`\\`options_max_daily_loss\` must be non-negative. Got: ${value}\\`; }\n  }",
  "updatedKey": "max_positions: {\n    default: 5,\n    max: 50,\n    min: 1,\n    description: 'Max concurrent market positions'\n  },\n  max_notional_per_trade: {\n    default: 5000,\n    min: 10,\n    description: 'Max dollar value per trade'\n  },\n  cooldown_minutes: {\n    default: 30,\n    min: 0,\n    max: 1440,\n    description: 'Minutes between trades for same symbol'\n  },\n  scan_interval_minutes: {\n    default: 5,\n    min: 1,\n    max: 60,\n    description: 'How often agent scans for signals'\n  },\n  options_max_delta: {\n    default: 0.75,\n    min: 0.15,\n    max: 0.75,\n    description: 'Max option delta for contract selection (widened for late-day 0DTE)'\n  },\n  options_min_delta: {\n    default: 0.15,\n    min: 0.15,\n    max: 0.75,\n    description: 'Min option delta for contract selection (widened for 0DTE)'\n  },\n  max_daily_loss_pct: {\n    default: 0.02,\n    min: 0,\n    max: 1,\n    description: 'Max daily loss as decimal (e.g., 0.02 = 2%)'\n  },\n  stop_loss_pct: {\n    default: 0.05,\n    min: 0,\n    max: 1,\n    description: 'Stop loss threshold as decimal'\n  },\n  take_profit_pct: {\n    default: 0.10,\n    min: 0,\n    max: 1,\n    description: 'Take profit threshold as decimal'\n  },\n  options_min_conviction: {\n    default: 5,\n    min: 1,\n    max: 10,\n    description: 'AI conviction score (1–10) to enter a trade'\n  },\n  options_scalp_take_profit_pct: {\n    default: 0.30,\n    min: 0,\n    max: 1,\n    description: 'Scalp take profit target as decimal'\n  },\n  options_scalp_stop_loss_pct: {\n    default: 0.25,\n    min: 0,\n    max: 1,\n    description: 'Scalp stop loss as decimal'\n  },\n  options_swing_take_profit_pct: {\n    default: 0.75,\n    min: 0,\n    max: 1,\n    description: 'Swing take profit target as decimal'\n  },\n  options_swing_stop_loss_pct: {\n    default: 0.40,\n    min: 0,\n    max: 1,\n    description: 'Swing stop loss as decimal'\n  }",
  "removedCode": "// Stash current config when dangerous mode is active\n    this._savedConfig = { ...this.config };\n    // Apply aggressive overrides on top of current config\n    for (const [key, value] of Object.entries(DANGEROUS_CONFIG)) { \n      if (key in this.config) {\n        this.config[key] = value;\n      }\n    }\n    this.dangerousMode = true;\n    this._persist();\n    console.log('[Policy] DANGEROUS MODE ENABLED — aggressive trading parameters active');\n    return { changed: true };\n  }",
  "removedCode": "// Restore the stashed config\n    if (this._savedConfig) {\n      this.config = { ...this._savedConfig };\n      this._savedConfig = null;\n    } else {\n      this.config = { ...DEFAULT_CONFIG };\n    }\n    this.dangerousMode = false;\n    this._persist();\n    console.log('[Policy] Dangerous mode DISABLED — restored previous config');\n    return { changed: true };\n  }",
  "updatedKey": "options_min_delta: {\n    default: 0.15,\n    min: 0.15,\n    max: 0.75,\n    description: 'Min option delta for contract selection (widened for 0DTE)'\n  },\n  options_max_delta: {\n    default: 0.75,\n    min: 0.15,\n    max: 0.75,\n    description: 'Max option delta for contract selection (widened for late-day 0DTE)'\n  }",
  "addedCategory": "Numeric Keys: \n  {\n    description: 'Percentage thresholds (0‑1 range)',\n    keys: ['max_daily_loss_pct', 'stop_loss_pct', 'take_profit_pct', 'min_sentiment_score', 'min_analyst_confidence', 'options_scalp_take_profit_pct', 'options_scalp_stop_loss_pct', 'options_swing_take_profit_pct', 'options_swing_stop_loss_pct', 'position_size_pct'],\n    unit: 'decimal',\n    range: [0, 1],\n    example: '0.05 = 5%'\n  },\n  {\n    description: 'Position & inventory controls',\n    keys: ['max_positions', 'scan_interval_minutes', 'cooldown_minutes', 'max_notional_per_trade', 'position_size_pct'],\n    unit: 'integer or %',\n    range: [1, 60] for scan_interval_minutes, [1, 50] for max_positions, [10, Infinity] for max_notional_per_trade,\n    example: 'max_positions defaults to 5, min 1, max 50'\n  },\n  {\n    description: 'Option delta limits',\n    keys: ['options_min_delta', 'options_max_delta'],\n    unit: 'decimal (0‑1)',\n    range: [0.15, 0.75],\n    example: 'options_min_delta = 0.15 means minimum 15%% delta'\n  }",
  "addedErrorExamples": [
    {
      "key": "max_daily_loss_pct",
      "exampleInvalid": "0.25",
      "error": "`max_daily_loss_pct` must be between 0 and 1 (e.g. 0.05 for 5%). Got: 0.25"
    },
    {
      "key": "options_min_delta",
      "exampleInvalid": "0.10",
      "error": "`options_min_delta` must be between 0.15 and 0.75. Got: 0.10"
    },
    {
      "key": "cooldown_minutes",
      "exampleInvalid": "3000",
      "error": "`cooldown_minutes` must be between 0 and 1440. Got: 3000"
    },
    {
      "key": "scan_interval_minutes",
      "exampleInvalid": "0",
      "error": "`scan_interval_minutes` must be at least 1. Got: 0"
    }
  ],
  "addedCleanupCode": "this._cleanExpiredTokens();",
  "updatedConfigVersionComment": "// Config version — increment when defaults change to trigger migration\nconst CONFIG_VERSION = 2;",
  "addedMigrationNote": "// Migrate stored config when code defaults change.\n// Only resets keys that were at old defaults — preserves user overrides\n// by checking against known old default values.\nif (savedVersion < CONFIG_VERSION) {",
  "addedMigrationCheck": "    if (savedVersion < CONFIG_VERSION) {",
  "addedPreserveNote": "// Only resets keys that were at old defaults — preserves user overrides\n// by checking against known old default values.",
  "updatedMigrationBlock": "if (savedVersion < CONFIG_VERSION) {\n      console.log(`[Policy] Migrating config from v${fromVersion} to v${CONFIG_VERSION}`);\n      // v0/v1 → v2: conviction lowered (7→5), delta range widened (0.25-0.60 → 0.15-0.75)\n      if (this.config.options_min_conviction === 7) {\n        this.config.options_min_conviction = DEFAULT_CONFIG.options_min_conviction;\n        console.log(`[Policy] Migrated options_min_conviction: 7 → ${DEFAULT_CONFIG.options_min_conviction}`);\n      }\n      if (this.config.options_min_delta === 0.25) {\n        this.config.options_min_delta = DEFAULT_CONFIG.options_min_delta;\n        console.log(`[Policy] Migrated options_min_delta: 0.25 → ${DEFAULT_CONFIG.options_min_delta}`);\n      }\n      if (this.config.options_max_delta === 0.60) {\n        this.config.options_max_delta = DEFAULT_CONFIG.options_max_delta;\n        console.log(`[Policy] Migrated options_max_delta: 0.60 → ${DEFAULT_CONFIG.options_max_delta}`);\n      }\n    }",
  "updatedDestructureMigration": "const savedVersion = this._storage.get('configVersion', 0);\n    if (savedVersion < CONFIG_VERSION) {",
  "newMigrationInsert": "console.log(`[Policy] Migration required from v${savedVersion} to v${CONFIG_VERSION}. Applying default overrides where needed.`);",
  "addedExplanationComment": "// Increment version when defaults change to force migration and prevent stale configs\nconst CONFIG_VERSION = 2;",
  "addedValidationToNumberKeys": "if (NUMERIC_KEYS.has(key)) {",
  "addedRangeCheckForNumeric": "if (key.includes('pct') && (value < 0 || value > 1)) {",
  "addedRangeCheckForMaxPositions": "if (key === 'max_positions' && (value < 1 || value > 50)) {",
  "addedRangeCheckForNotional": "if (key === 'max_notional_per_trade' && value < 10) {",
  "addedRangeCheckForCooldown": "if (key === 'cooldown_minutes' && (value < 0 || value > 1440)) {",
  "addedRangeCheckForScanInterval": "if (key === 'scan_interval_minutes' && (value < 1 || value > 60)) {",
  "addedRangeCheckForDelta": "if (key.includes('delta') && (value < 0 || value > 1)) {"
}